# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f38798119c873a129246190702887f78356cc271493fe770118464131dbf31167e5d51e8c26a2c3cc0f23c237b47085a448401de3b513cf591f5534a18e2e93

test:
  secret_key_base: 356216b9deadfba17efb466e98083cf1e13ac83cd8809e35ffc4e5bd5627e4528fcf56187dd041b352f67a02d95eb983b0d4f4c7c1046a1fa93c78a13427b67d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
